name: "Haskell"

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - ".github/workflows/haskell.yml"
      - "src/**"
      - "package.yaml"
      - "stack*.yaml"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build"
    strategy:
      fail-fast: false
      matrix:
        resolver:
          - stack-lts12
          - stack-lts16
          - stack-lts19

    runs-on: ubuntu-latest

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: "Build with Stack"
        uses: mbg/actions/stack/build@v0.2
        with:
          resolver: ${{ matrix.resolver }}
