name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - ".github/workflows/haskell.yml"
      - "src/**"
      - "package.yaml"
      - "stack*.yaml"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        resolver:
          - stack-lts12
          - stack-lts16
          - stack-lts19

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2
        id: install-haskell
        with:
          stack-no-global: true
          enable-stack: true
          stack-setup-ghc: true
          stack-version: "latest"

      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v4
        with:
          path: ${{ steps.install-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-${{ hashFiles('moss.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install dependencies
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --only-dependencies --fast --haddock

      - name: Build
        id: build
        run: |
          stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --fast --haddock
