name: "Stackage Nightly"

on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/stackage-nightly.yml"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: "Build with Stack nightly"
        uses: mbg/actions/stack/nightly@v0.1
        with:
          create-issue: "true"
